"use client";
import { useState, useCallback, useEffect } from "react";
import BlockchainCanvas from "@/components/BlockchainCanvas";

interface TrustReport {
  id: string;
  trustScore: number;
  riskLevel: string;
  scamRisk: string;
  liquidityStatus: string;
  ownershipRisk: string;
  holderConcentration: string;
  contractRisks: string;
  aiSummary: string;
  verified: boolean;
  createdAt: string;
}

interface Analysis {
  id: string;
  tokenAddress: string;
  tokenName: string | null;
  tokenSymbol: string | null;
  createdAt: string;
  trustReport: TrustReport | null;
}

interface ReportsResponse {
  analyses: Analysis[];
  total: number;
  filters: { q: string | null; riskLevel: string | null; address: string | null };
  error?: string;
}

function Skeleton({ h = "h-4", w = "w-full" }: { h?: string; w?: string }) {
  return <div className={`skeleton ${h} ${w} rounded-lg`} />;
}

const RISK_LEVELS = ["Low", "Medium", "High", "Critical"];

const riskColor = (level: string) => {
  return ({
    Low: "var(--wb-trust-excellent)",
    Medium: "var(--wb-trust-review)",
    High: "var(--wb-trust-risk)",
    Critical: "var(--wb-trust-critical)"
  }[level] || "var(--wb-color-text-muted)");
};

export default function ReportsPage() {
  const [q, setQ] = useState("");
  const [riskLevel, setRiskLevel] = useState<string | null>(null);
  const [data, setData] = useState<ReportsResponse | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [saving, setSaving] = useState<string | null>(null);
  const [savedIds, setSavedIds] = useState<Set<string>>(new Set());
  const [showSavedOnly, setShowSavedOnly] = useState(false);

  const load = useCallback(async (query: string, level: string | null) => {
    setLoading(true);
    setError(null);
    try {
      const params = new URLSearchParams();
      if (query.trim()) params.set("q", query.trim());
      if (level) params.set("riskLevel", level);
      params.set("limit", "50");
      const res = await fetch(`/api/report?${params.toString()}`);
      const json = await res.json();
      if (!res.ok) {
        setError(json.error || "Failed to load reports");
        setLoading(false);
        return;
      }
      setData(json);
    } catch {
      setError("Network error. Please try again.");
    }
    setLoading(false);
  }, []);

  useEffect(() => {
    const t = setTimeout(() => load(q, riskLevel), 300);
    return () => clearTimeout(t);
  }, [q, riskLevel, load]);

  useEffect(() => {
    async function loadSaved() {
      try {
        const res = await fetch("/api/report/saved");
        if (res.ok) {
          const json = await res.json();
          setSavedIds(new Set((json.ids || []).map((id: string) => id.toLowerCase())));
        }
      } catch {}
    }
    loadSaved();
  }, []);

  const toggleSave = async (analysisId: string) => {
    setSaving(analysisId);
    try {
      const res = await fetch("/api/report", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ analysisId }),
      });
      if (res.ok) {
        const json = await res.json();
        setSavedIds((prev) => {
          const next = new Set(prev);
          if (json.saved) next.add(analysisId.toLowerCase());
          else next.delete(analysisId.toLowerCase());
          return next;
        });
      }
    } catch {}
    setSaving(null);
  };

  const visible = showSavedOnly
    ? (data?.analyses || []).filter((a) => savedIds.has(a.id.toLowerCase()))
    : data?.analyses || [];

  return (
    <div className="page-in relative min-h-screen">
      <BlockchainCanvas />
      <div className="fixed inset-0 pointer-events-none" style={{ background: "var(--wb-color-hero-overlay)", zIndex: 1 }} />

      <div style={{ position: "relative", zIndex: 2 }}>
        <div className="wb-container py-[72px]">
          <div className="mb-8">
            <h1 style={{ fontFamily: "var(--wb-font-display)", fontSize: "clamp(1.8rem,3.5vw,2.5rem)", fontWeight: 400, color: "var(--wb-color-text-primary)", marginBottom: "0.5rem" }}>
              Security Reports
            </h1>
            <p style={{ color: "var(--wb-color-text-secondary)", fontSize: "0.9375rem" }}>
              Search and filter every AI trust report generated by WaveBlock.
            </p>
          </div>

          <div className="wb-card p-5 mb-8">
            <div className="flex flex-col sm:flex-row gap-3">
              <input
                type="text"
                value={q}
                onChange={(e) => setQ(e.target.value)}
                placeholder="Search by token name, symbol, or contract address…"
                className="wb-input flex-1"
                style={{
                  padding: "0.75rem 1.25rem", border: "1.5px solid var(--wb-color-border-strong)",
                  borderRadius: "var(--wb-radius-md)", fontFamily: "var(--wb-font-ui)",
                  fontSize: "0.9rem", background: "var(--wb-color-surface)",
                  outline: "none", transition: `all var(--wb-duration-fast) var(--wb-ease-standard)`,
                }}
                onFocus={(e) => { e.target.style.borderColor = "var(--wb-color-primary)"; e.target.style.boxShadow = "var(--wb-shadow-focus)"; }}
                onBlur={(e) => { e.target.style.borderColor = "var(--wb-color-border-strong)"; e.target.style.boxShadow = "none"; }}
              />
              <div className="flex gap-2">
                {RISK_LEVELS.map((level) => (
                  <button
                    key={level}
                    onClick={() => setRiskLevel(riskLevel === level ? null : level)}
                    style={{
                      background: riskLevel === level ? riskColor(level) : "transparent",
                      color: riskLevel === level ? "var(--wb-color-background)" : riskColor(level),
                      border: `1px solid ${riskColor(level)}`,
                      borderRadius: "var(--wb-radius-sm)", padding: "0.5rem 1rem", fontSize: "0.8rem",
                      fontWeight: 600, cursor: "pointer", transition: `all var(--wb-duration-fast) var(--wb-ease-standard)`,
                    }}
                  >
                    {level}
                  </button>
                ))}
              </div>
            </div>
            <div className="mt-3 flex items-center gap-3">
              <label style={{ display: "flex", alignItems: "center", gap: "0.5rem", color: "var(--wb-color-text-secondary)", fontSize: "0.85rem", cursor: "pointer" }}>
                <input type="checkbox" checked={showSavedOnly} onChange={(e) => setShowSavedOnly(e.target.checked)} />
                Saved only
              </label>
              {data && <span style={{ color: "var(--wb-color-text-muted)", fontSize: "0.8rem" }}>{visible.length} of {data.total} reports</span>}
            </div>
          </div>

          {loading && (
            <div className="space-y-3 animate-pulse">
              {[1, 2, 3, 4].map((i) => (
                <div key={i} className="wb-card p-5 space-y-2">
                  <Skeleton h="h-5" w="w-48" />
                  <Skeleton h="h-3" w="w-72" />
                </div>
              ))}
            </div>
          )}

          {error && (
            <div className="wb-card p-4 mb-8" style={{ border: "1px solid rgba(239,68,68,0.22)", background: "rgba(239,68,68,0.07)" }}>
              <p style={{ color: "var(--wb-color-danger)", fontSize: "0.875rem", fontWeight: 600 }}>{error}</p>
            </div>
          )}

          {data && !loading && visible.length === 0 && (
            <div className="text-center py-16">
              <h2 style={{ fontFamily: "var(--wb-font-display)", fontSize: "1.3rem", fontWeight: 400, color: "var(--wb-color-text-primary)", marginBottom: "0.5rem" }}>
                No reports found
              </h2>
              <p style={{ color: "var(--wb-color-text-secondary)", fontSize: "0.9rem" }}>
                {showSavedOnly ? "You haven't saved any reports yet." : "Try a different search, or run a scan on the dashboard."}
              </p>
            </div>
          )}

          {data && !loading && (
            <div className="space-y-4">
              {visible.map((a) => {
                const color = riskColor(a.trustReport?.riskLevel || "Medium");
                return (
                  <div key={a.id} className="wb-card p-5">
                    <div className="flex flex-wrap items-center justify-between gap-3 mb-3">
                      <div className="flex items-center gap-3">
                        <span
                          className="px-3 py-1 rounded-full text-xs font-bold"
                          style={{ background: `${color}18`, color }}
                        >
                          {a.trustReport?.riskLevel || "N/A"}
                        </span>
                        <div>
                          <p style={{ fontWeight: 600, color: "var(--wb-color-text-primary)", fontSize: "0.95rem" }}>
                            {a.tokenName || "Unknown"} <span style={{ color: "var(--wb-color-text-muted)" }}>({a.tokenSymbol || "???"})</span>
                          </p>
                          <p style={{ color: "var(--wb-color-text-muted)", fontSize: "0.75rem", fontFamily: "var(--wb-font-mono)" }}>
                            {a.tokenAddress.slice(0, 10)}...{a.tokenAddress.slice(-6)}
                          </p>
                        </div>
                      </div>
                      <div className="flex items-center gap-3">
                        <span style={{ fontWeight: 700, fontSize: "1rem", color }}>
                          {a.trustReport?.trustScore ?? "—"}/100
                        </span>
                        <button
                          onClick={() => toggleSave(a.id)}
                          disabled={saving === a.id}
                          title="Save report"
                          style={{
                            background: savedIds.has(a.id.toLowerCase()) ? "var(--wb-color-primary-soft)" : "transparent",
                            border: `1px solid ${savedIds.has(a.id.toLowerCase()) ? "rgba(79,124,255,0.3)" : "var(--wb-color-border)"}`,
                            borderRadius: "var(--wb-radius-sm)", padding: "0.4rem 0.75rem", fontSize: "0.8rem",
                            fontWeight: 600, color: savedIds.has(a.id.toLowerCase()) ? "var(--wb-color-primary)" : "var(--wb-color-text-secondary)",
                            cursor: saving === a.id ? "not-allowed" : "pointer",
                          }}
                        >
                          {savedIds.has(a.id.toLowerCase()) ? "✓ Saved" : "☆ Save"}
                        </button>
                      </div>
                    </div>
                    <p style={{ color: "var(--wb-color-text-secondary)", fontSize: "0.85rem", lineHeight: 1.6, marginBottom: "0.75rem" }}>
                      {a.trustReport?.aiSummary || "No AI summary available."}
                    </p>
                    <div className="flex flex-wrap gap-2 text-xs">
                      {[
                        { label: "Scam Risk", value: a.trustReport?.scamRisk },
                        { label: "Liquidity", value: a.trustReport?.liquidityStatus },
                        { label: "Ownership", value: a.trustReport?.ownershipRisk },
                        { label: "Holders", value: a.trustReport?.holderConcentration },
                        { label: "Contract", value: a.trustReport?.contractRisks },
                      ].filter((x) => x.value).map((x) => (
                        <span key={x.label} style={{ background: "var(--wb-color-surface)", border: "1px solid var(--wb-color-border)", borderRadius: "var(--wb-radius-xs)", padding: "0.25rem 0.625rem", color: "var(--wb-color-text-muted)" }}>
                          {x.label}: <strong style={{ color: "var(--wb-color-text-secondary)" }}>{x.value}</strong>
                        </span>
                      ))}
                    </div>
                    <p style={{ color: "var(--wb-color-text-muted)", fontSize: "0.72rem", marginTop: "0.75rem" }}>
                      {new Date(a.createdAt).toLocaleString()}
                    </p>
                  </div>
                );
              })}
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
